### DISCUSSION TITLE
Enum attribute for SwaggerSchema

### DISCUSSION THREAD

**Discussion by alexministrybrands** [domaindrivendev/Swashbuckle.AspNetCore#3167] [Q&A]
Hello. I'm using Swashbuckle for one of my API projects and want to handle requests with string enum fields. I don't want to use Enum object for a request property, because it requires additional logic here for json conversion and additional logic for validation. Also, the shape of the error looks weird for me in case when json cannot convert the provided string to Enum class value.

What I would expect from Swashbuckle is a possibility to use SwaggerSchema on request string property, but tell that it has to be an enum. So something like that:
```
using Swashbuckle.AspNetCore.Annotations;

public sealed record CreateUserRequest
{
  [SwaggerSchema("The gender of the user.", Format = "string", Enum = Gender)] // or something similar, so that docs will be created with enum provided...
  public string? Gender { get; set; }
}
```

so that my openapi.yaml file would look like this for that request:
```
gender:
          type: string
          enum: ['male', 'female', 'other']
          nullable: true
          example: "male"
```

Could you let me know if I can somehow achieve that?
