### ISSUE TITLE
Can't generate enum item descriptions

### ISSUE THREAD

**Issue by Mazas17** [domaindrivendev/Swashbuckle.AspNetCore#1685]
According to OpenAPI documentation, it is possible to add description to single enum item:
```
      parameters:
        - in: query
          name: sort
          schema:
            type: string
            enum: [asc, desc]
          description: >
            Sort order:
             * `asc` - Ascending, from A to Z
             * `desc` - Descending, from Z to A
```
https://swagger.io/docs/specification/data-models/enums/

How to do that with swashbuckle? Can't find any documentation
