### ISSUE TITLE
Could not load file or assembly Swashbuckle.AspNetCore.Swagger for CLI on GitHub Action

### ISSUE THREAD

**Issue by fabich** [domaindrivendev/Swashbuckle.AspNetCore#2022]
Hi

After updating the CLI from `5.4.1` to `6.0.7` we are getting the following error on our GitHub Action build:
```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Swashbuckle.AspNetCore.Swagger, Version=6.0.7.0, Culture=neutral, PublicKeyToken=62657d7474907593'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Swashbuckle.AspNetCore.Swagger, Version=6.0.7.0, Culture=neutral, PublicKeyToken=62657d7474907593'
   at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_3(IDictionary`2 namedArgs)
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 59
   at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 111
```

Our GitHub Action:
```
name: Run OpenAPI diff check

on: [pull_request]

jobs:
  create-old-files:
    name: Create OLD spec files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: <Project>
          ref: develop
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
      - name: Create Result Directory
        run: mkdir src
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/<Project>/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GPR_READ}}
      - name: Restore
        run: dotnet restore
        working-directory: ./<Project>
      - name: Build
        run: dotnet build
        working-directory: ./<Project>
      - name: Install Swashbuckle.AspNetCore.Cli
        run: |
          dotnet new tool-manifest
          dotnet tool install Swashbuckle.AspNetCore.Cli --version 6.0.7
      - name: Create OpenAPI specification files
        working-directory: ./<Project>/<Project>.APP
        run: |
          dotnet swagger "tofile" --output "../../src/pdf.json" "./bin/Debug/net5.0/<Project>.APP.dll" pdf
      - name: Copy OpenAPI specification files
        run: cp ./<Project>/<Project>.APP/*.json ../src/
        working-directory: ./<Project>
      - name: Upload OpenAPI specification files
        uses: actions/upload-artifact@v1
        with:
          name: old-files
          path: src
```

The .csproj file:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1591;</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="pdf.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.17.0" />
    <PackageReference Include="Autofac" Version="6.1.0" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="7.1.0" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.1.1" />
    <PackageReference Include="FluentValidation" Version="9.5.1" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="9.5.1" />
    <PackageReference Include="IdentityServer4.AccessTokenValidation" Version="3.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="5.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="4.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="4.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.NodeServices" Version="3.1.12" />
    <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="5.0.3" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="5.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.AzureAppServicesIntegration" Version="5.0.3" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\css\print.css" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\<Project>.BLL\<Project>.BLL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Views\EtatCreator\_AllEtatViews.cshtml">
      <Pack>$(IncludeRazorContentInPack)</Pack>
    </Content>
    <Content Update="Views\EtatCreator\_ComponentEtatViewPosition.cshtml">
      <Pack>$(IncludeRazorContentInPack)</Pack>
    </Content>
    <Content Update="Views\EtatCreator\_SingleEtatView.cshtml">
      <Pack>$(IncludeRazorContentInPack)</Pack>
    </Content>
  </ItemGroup>
</Project>
```

Any idea what might cause this issue?
