### ISSUE TITLE
Support <example> xml comments on fields

### ISSUE THREAD

**Issue by matdube** [domaindrivendev/Swashbuckle.AspNetCore#742]
In swagger you can specify an example value for a property. ie:
```
definitions:
  person:
    type: "object"
    properties:
      name:
        type: "string"
        example: "Joe"
```

Swashbuckle could generate it from the xml comments (https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/example) just like the summary
